--- bak.Makefile	2017-11-16 10:20:05.372329421 +0100
+++ Makefile	2017-11-16 11:10:15.520329062 +0100
@@ -10,6 +10,7 @@
 subdir-$(CONFIG_SECURITY_APPARMOR)	+= apparmor
 subdir-$(CONFIG_SECURITY_YAMA)		+= yama
 subdir-$(CONFIG_SECURITY_LOADPIN)	+= loadpin
+subdir-$(CONFIG_SECURITY_THEREST)	+= therestrictor
 
 # always enable default capabilities
 obj-y					+= commoncap.o
